# TODO: merge into PR & CI pipeline after testing.
# TODO: also test fluent UI master actions, such as storing data to db (ask miro if there's a way to test this with dummy data)
# temporary pipeline for testing fluent repo CI.
pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables

pool: 'Self Host Ubuntu'

steps:
  - template: azure-pipelines.tools.yml

  - script: |
      yarn
    displayName: yarn

  # - script: |
  #     yarn just perf-test
  #   workingDirectory: apps/perf-test
  #   displayName: Perf Test

  # - script: |
  #     if [ $BUILD_REASON == "PullRequest" ] && [ ! -z $DANGER_GITHUB_API_TOKEN ]; then
  #       yarn danger ci
  #     elif [ $BUILD_REASON != "PullRequest" ]; then
  #       echo "Skipping Danger JS because BUILD_REASON ${BUILD_REASON} != PullRequest"
  #     else
  #       echo "Skipping Danger JS because API token wasn't found"
  #     fi

  - script: |
      yarn danger ci
    env:
      DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)
